### PR TITLE
OO#102 adding price in the abos overview

### PR DESCRIPTION
**Pull request by mcmpp**

### CODE REVIEW

**Review by AlwinEgger — COMMENTED** [review]
This would display the price on the abotyp. But what if this Abo has a specific price, then the information is wrong.

And this should also be done the same way on the zusatzabo-overview.

**Comment by mcmpp** [comment]
the logic to see if the value needs to be taken from the subscription or from the subscription type is on the html. For the zusatzabo, we do not have the "view all columns" option. Do you think that we should add it or simply add the price column?

**Comment by AlwinEgger** [comment]
> the logic to see if the value needs to be taken from the subscription or from the subscription type is on the html. For the zusatzabo, we do not have the "view all columns" option. Do you think that we should add it or simply add the price column?

Ok, display logic makes sense. 

I would add the "eye" to the Zusatzabo-Overview since there is a request to also display additional Hauptabo-information (but this is more complex since we need to load more data).

**Comment by mcmpp** [comment]
I am adding the eye and the price for the zusatzabo in this ticket. We leave the new parameter for a new ticket

**Review by AlwinEgger — APPROVED** [review]

**Pull request merged**
